name: Spring Boot & Gradle CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 기본 체크아웃
      - name: checkout
        uses: actions/checkout@v3

      # JDK version 설정
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # main yaml 파일 쓰기
      - name: Set main yaml
        run: |
          # main 설정 파일 디렉토리로 이동
          cd ./src/main/resources
          
          # application-database.yaml 파일 생성
          touch ./application-database.yaml
          # GitHub-Actions 에서 설정한 값을 application-database.yaml 파일에 쓰기
          echo "${{ secrets.MAIN_DATABASE_YML }}" >> ./application-database.yaml
        shell: bash

      # 그래들 테스트 실행
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew --info test
